name: Run Ansible Playbooks

on:
  - pull_request

jobs:
  check-syntax:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Change to Ansible directory and clone Ansible Repo
      run: cd ansible-workflows && git clone https://github.com/rubrikinc/rubrik-modules-for-ansible.git
    - name: Stage Ansible files
      run: cd ansible-workflows/rubrik-modules-for-ansible/ && cp -R rubrikinc ../.. && cp ansible.cfg ../..
    - name: Check syntax
      run: ansible-playbook --verbose --syntax-check ansible-workflows/*.yaml
